Improve Agents preview page load when there are no agents
wazuh/wazuh-dashboard-plugins pull request #6185
Opened 2023-11-30 15:20 UTC by lucianogorza

### Description
When there are no registered agents and the `Agents preview` page is loaded, the component with the dashboard and the list of agents is always shown first for a moment, and then the component to register an agent is displayed. This PR fixes in the case where there are no registered agents so that the component with the dashboard and the list is not shown first but directly displays the component to register an agent.
 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6175

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-12-05 17:49 UTC, asteriscos requested changes
CR: :x:  Changelog entry should be placed in fixed. As it's not something new o a change in the behaviour of a feature.

Test: :heavy_check_mark: 

The agent's dashboard is not seen as it loads.

### Overview -> Register Agent

https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/2c790153-65bf-4797-a327-3a31b6e7e052

### Agents initial load

https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/6adb56c9-844f-4993-9363-f19f170ebae1

2023-12-07 09:31 UTC, yenienserrano reviewed
Test: ✅ 
CR: Comment

2023-12-07 09:31 UTC, yenienserrano commented on plugins/main/public/controllers/agent/components/agents-preview.js
> +          <div class='md-padding md-padding-top-16'>
shouldn't it be className?

2023-12-07 13:31 UTC, lucianogorza commented on plugins/main/public/controllers/agent/components/agents-preview.js
> +          <div class='md-padding md-padding-top-16'>
Done

2023-12-07 15:00 UTC, yenienserrano approved these changes

2023-12-11 12:56 UTC, merged