Implement journald log collection feature
wazuh/wazuh-dashboard-plugins pull request #6572
Opened 2024-04-04 11:26 UTC by JuanGarriuz

### Description
[Describe what this change achieves]
 
### Issues Resolved

https://github.com/wazuh/wazuh-dashboard-plugins/issues/6564

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-04-18 14:57 UTC, Tostti commented on plugins/main/public/controllers/management/components/management/configuration/util-components/configuration-setting.js
>  import { EuiFieldText, EuiSpacer, EuiTextAlign } from '@elastic/eui';
**Thought**: these imports could be in a single line, as they comes from the same place

2024-04-18 15:01 UTC, Tostti commented
# Test 🟢 
 
- [x] Go to Server Management > Endpoints summary > Click on an Agent > Configuration > Log collection and check that journald tab is available and shows expected results.
- [x] Check that Filters render correctly and the results are as expected
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/a031ce82-9f1f-4ed5-a5ea-6420dc2d8f67)

- [x] Move between different agents to check that the filters show related results and only render the filters that have results
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/3e5b35a2-b37b-40db-989f-434a86f371e6)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/1bfb9857-151d-4e3e-93b6-9f557e8ef245)

2024-04-18 15:02 UTC, Tostti submitted a review, later dismissed
Test ✅ 
CR ✅ 

LGTM

2024-04-23 15:55 UTC, asteriscos requested changes
Test: :heavy_check_mark: 
CR: Requested minor changes

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/a6623398-63a5-4321-ba55-6343f63eb1d3)

2024-04-23 15:55 UTC, asteriscos commented on plugins/main/public/controllers/management/components/management/configuration/log-collection/log-collection-journald.js
> +          <WzConfigurationSettingsGroup
In case there's only 1 log I think it would be useful to also render de Setting Header, like when there are more than 1.

2024-04-23 15:55 UTC, asteriscos commented on plugins/main/public/controllers/management/components/management/configuration/util-components/configuration-settings-header.js
> +              {(help || info) && (
Beware that the `help` variable can be a falsy value and then the `WzHelpButtonPopover` expects an array. This could cause an exception.

2024-04-24 10:25 UTC, asteriscos approved these changes
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/a1301d32-24c3-48ad-8f39-626b714c974a)

2024-04-24 16:15 UTC, Tostti commented
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/e45c0d47-68b4-4488-b987-02c820f2a95b)

LGTM

2024-04-24 16:16 UTC, Tostti approved these changes

2024-04-24 16:16 UTC, merged