Fix styles in small height viewports
wazuh/wazuh-dashboard-plugins pull request #6747
Opened 2024-06-05 11:04 UTC by JuanGarriuz

### Description

Fix fix the discover table small viewport and remove duplicated code in css classes.
 
### Issues Resolved

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6740

### Evidence

https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/a1d4ef7e-e263-401c-a57b-3fde36189d1c

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-06-06 13:59 UTC, yenienserrano commented
### Test

- [ ] 🟡 Check that inventory tabs around the app are rendered correctly (The tab selector doesn't must stay on the top of view)

<details><summary>Details</summary>

I don't know if I understood the issue correctly but maybe you also want to remove the scroll inside the table so that the page only has the scroll.

https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/922308d2-95ba-465d-a5bd-346ea70063b4

</details> 

- [ ] 🔴  Check full screen in the inventory tab table works as expected.

<details><summary>Details</summary>

🟢 Events

<img width="1510" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/04777632-55d1-484e-a5eb-6398c3b3cdda">

🔴 Threat Hunting / dashboard 

Table options are not visible

<img width="1502" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/7d2612c3-099e-4164-b74e-701b6dd87069">

</details>

2024-06-06 20:15 UTC, jbiset requested changes
## CR: In Progress - Comment added

## Test UI :red_circle: 

### Check that inventory tabs around the app are rendered correctly (The tab selector doesn't must stay on the top of view) :red_circle:  

There is a difference between table scrolling in Chrome and Firefox. In Chrome the table does not have a scrollbar and grows by the size of the table. On the other hand, in Firefox the table does not grow and a scroolbar appears for the body of the table.

- Chrome

[Evidence_1_Chrome.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/71cdb754-4495-47c6-942f-990cd1c62cab)


- Firefox

[Evidence_1_Firefox.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/945c55e2-9ee8-41f3-be31-a55900179a2e)


### Check full screen in the inventory tab table works as expected. :green_circle: 

- Chrome

[Evidence_2_Chrome.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/79c32e72-4997-4b1f-82bf-396cc00c5e4e)

- Firefox

[Evidence_2_Firefox.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/33063dd7-4c36-4bf2-a8cc-1079f66d0f90)

2024-06-06 20:36 UTC, lucianogorza commented on plugins/main/public/components/common/wazuh-discover/render-columns.tsx
> -  },
You are right, the column was removed.

2024-06-06 20:38 UTC, lucianogorza commented on plugins/main/public/components/common/wazuh-discover/render-columns.tsx
> -  },
The column was removed because the hook useDataGrid already formats date values.

2024-06-07 19:22 UTC, yenienserrano commented
### Test

#### Data grid

- [ ] Check that inventory tabs around the app are rendered correctly (The tab selector doesn't must stay on the top of view)
- [ ] Check that the full screen in the inventory tab table works as expected.
- [ ] Check Threat intelligence > Threat Hunting > dashboard view render correctly

<details><summary>Details</summary>



</details> 

#### Controls flyout details

- [ ] In Security operations > TSC > Controls checks Flyout > Rule > Details don't shows data in JSON format 

<details><summary>Details</summary>


</details> 

#### Fix date format with pinned agent in Mitre att&ck -> Framework flyout

- With pinned agent in Mitre att&ck -> Framework flyout, check the date is formated

<details><summary>Details</summary>


</details>

2024-06-07 22:47 UTC, jbiset requested changes
## CR: :green_circle: 

## Test UI :green_circle:   

### Check that inventory tabs around the app are rendered correctly (The tab selector doesn't must stay on the top of view) :green_circle:  


- Chrome

[Evidence_1_Chrome_ok.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/456b9f2b-b80e-47b7-a3dd-d369b0e348f0)

- Firefox

[Evidence_1_Firefox_ok.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/8ff07556-1f26-4c79-b59a-2af83db6ec4a)

### Check full screen in the inventory tab table works as expected. :green_circle: 

- Chrome

[Evidence_2_Chrome.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/79c32e72-4997-4b1f-82bf-396cc00c5e4e)

- Firefox

[Evidence_2_Firefox.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/33063dd7-4c36-4bf2-a8cc-1079f66d0f90)


### Check Threat intelligence > Threat Hunting > dashboard view render correctly :green_circle:  

- Chrome

[Evidence_3_Chrome_ok.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/bf367aef-027f-410c-a8d0-e5301821b37b)

- Firefox

[Evidence_3_Firefox_ok.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/2b093989-52b6-41aa-9732-fc469b0f7c02)

2024-06-10 12:40 UTC, jbiset approved these changes

2024-06-10 13:38 UTC, yenienserrano approved these changes
LGTM

2024-06-10 14:49 UTC, merged