Add feature to filter by field in the events table rows
wazuh/wazuh-dashboard-plugins pull request #6991
Opened 2024-09-11 14:26 UTC by guidomodarelli

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-09-13 08:59 UTC, JuanGarriuz commented
### Test

![image](https://github.com/user-attachments/assets/ff104743-5b68-47d4-b566-272f3c5fc359)

2024-09-13 09:12 UTC, JuanGarriuz commented on plugins/main/public/components/common/data-grid/use-data-grid.ts
> +  const [columns /* , setColumns */] =
Why is it commented?

> /* , setColumns */

2024-09-13 17:17 UTC, guidomodarelli commented on plugins/main/public/components/common/data-grid/use-data-grid.ts
> +  const [columns /* , setColumns */] =
Because it is not in use.

2024-09-16 17:34 UTC, asteriscos requested changes
Test: :red_circle: 

Please check that the buttons don't seem to work after changing the page.

![Peek 2024-09-16 19-33](https://github.com/user-attachments/assets/6a36edf8-a425-49f4-8e28-d4349c432ef1)

![image](https://github.com/user-attachments/assets/03fcc09d-0f72-45f6-86d4-64019df242bb)

2024-09-16 19:12 UTC, Machi3mfl approved these changes
CR: ✅ 
Test: ✅ 

<img width="1512" alt="Screenshot 2024-09-16 at 16 15 51" src="https://github.com/user-attachments/assets/1d894b95-9651-4fde-abf2-71d517e25fe4">

<img width="1511" alt="Screenshot 2024-09-16 at 16 15 35" src="https://github.com/user-attachments/assets/268b9383-f748-43f1-a744-c0134f745d63">

2024-09-16 20:58 UTC, asteriscos approved these changes

2024-09-17 08:22 UTC, JuanGarriuz approved these changes
LGTM!!

2024-09-17 08:24 UTC, merged