Bug/25617 the automatic page refresh is not working
wazuh/wazuh-dashboard-plugins pull request #7016
Opened 2024-09-25 14:35 UTC by guidomodarelli

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2024-09-27 20:14 UTC, chantal-kelm submitted a review, later dismissed
CR: ✅ 
TEST: ✅ 


https://github.com/user-attachments/assets/79ec5426-e87f-4b75-877a-b085575bb528

2024-09-30 12:04 UTC, Machi3mfl requested changes
The `include time filters` feature doesn't work


https://github.com/user-attachments/assets/db487220-99ff-45c9-a0d7-619b0bf4eff7

2024-10-01 19:50 UTC, Machi3mfl approved these changes
https://github.com/user-attachments/assets/2e7db1e4-3574-428d-a5cb-497839dac89e

2024-10-08 14:26 UTC, yenienserrano approved these changes
LGTM 🟢 


https://github.com/user-attachments/assets/e0452081-807f-4cfe-bbf3-209d121ee3a4

2024-10-09 07:27 UTC, Desvelao commented on CHANGELOG.md
> +- Fixed the automatic page refresh [#7016](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7016)
**though**: Could you elaborate where the fix is affecting? It is not clear to me.

2024-10-15 14:21 UTC, guidomodarelli commented
The resolution for this issue can be found in the pull request available at: https://github.com/wazuh/wazuh-dashboard-plugins/pull/7090.

This resolution also addressed a performance concern.

2024-10-15 14:21 UTC, closed without merging