Enhacement/7027 changed mitre description
wazuh/wazuh-dashboard-plugins pull request #7032
Opened 2024-09-30 11:01 UTC by JuanGarriuz

### Description

- Mitre feature: changed its current description by `Explore security alerts mapped to adversary tactics and techniques for better threat understanding.`
 
### Issues Resolved

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7027

### Evidence

![image](https://github.com/user-attachments/assets/20b107bd-9565-4ebd-9458-0aca1aa4be77)

### Test

- Check mitre overview description

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-09-30 16:29 UTC, guidomodarelli reviewed
https://github.com/wazuh/wazuh-dashboard-plugins/blob/fc92c443b813e47bf09ef1b01cc77217023c5a06/plugins/main/common/wazuh-modules.ts#L112 

```diff
diff --git a/plugins/main/common/wazuh-modules.ts b/plugins/main/common/wazuh-modules.ts
index 341300f65..ec327ed57 100644
--- a/plugins/main/common/wazuh-modules.ts
+++ b/plugins/main/common/wazuh-modules.ts
@@ -109,7 +109,7 @@ export const WAZUH_MODULES = {
     title: 'MITRE ATT&CK',
     appId: 'mitre-attack',
     description:
-      'Security events from the knowledge base of adversary tactics and techniques based on real-world observations',
+      'Explore security alerts mapped to adversary tactics and techniques for better threat understanding',
   },
   syscollector: {
     title: 'Inventory data',
```

2024-09-30 17:21 UTC, Machi3mfl approved these changes
CR: ✅ 
Test: ✅ 

### Before

<img width="751" alt="Screenshot 2024-09-30 at 2 20 00 PM" src="https://github.com/user-attachments/assets/3afacf46-7863-42df-b2d5-3ef247a1a427">


### After

<img width="753" alt="Screenshot 2024-09-30 at 2 19 50 PM" src="https://github.com/user-attachments/assets/25c91418-f073-4570-94d9-4786920261a4">

2024-10-01 14:09 UTC, asteriscos requested changes
CR: :red_circle:

2024-10-01 14:09 UTC, asteriscos commented on CHANGELOG.md
> +- Changed MITRE ATT%CK overview description [#7032] (https://github.com/wazuh/wazuh-dashboard-plugins/pull/7032)
Please change the `%` character to `&`

2024-10-02 16:26 UTC, asteriscos approved these changes
LGTM :green_circle:

2024-10-02 16:26 UTC, Machi3mfl approved these changes

2024-10-02 16:45 UTC, merged