Increase the font size of the kpi subtitles and the features descriptions
wazuh/wazuh-dashboard-plugins pull request #7033
Opened 2024-09-30 11:29 UTC by guidomodarelli

### Description
Text sizes: We want to increase the font size of the KPI subtitles and the features descriptions.
 
### Issues Resolved
[#7027](https://github.com/wazuh/wazuh-dashboard-plugins/issues/7027) 

### Evidence
![image](https://github.com/user-attachments/assets/2dd302e0-d5bb-4272-b1a1-ec1a8573be13)

### Test
Go to Overview page and check the size of the KPI subtitles and the features descriptions

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2024-09-30 11:50 UTC, Machi3mfl requested changes
The `include time filters` doesn't work


https://github.com/user-attachments/assets/397ad212-2606-443f-b43e-4a34e454b586

2024-10-01 13:49 UTC, Tostti requested changes
Test 🟢 
![image](https://github.com/user-attachments/assets/7cd81485-f3dc-4ed1-a4cc-2aa81ecb6e5a)

CR 🟢 

Tests 🔴  
Please upgrade the snapshots

2024-10-01 13:54 UTC, asteriscos approved these changes
CR: :green_circle: 
Test: :green_circle: 

![image](https://github.com/user-attachments/assets/d48b1392-44f4-45dc-b1e0-eb0f13e740d9)


![image](https://github.com/user-attachments/assets/199ef78d-93ee-4172-962e-8af3ebc9ac9c)

2024-10-01 13:58 UTC, asteriscos approved these changes

2024-10-01 14:04 UTC, Tostti approved these changes

2024-10-01 14:48 UTC, merged