Change agents summary no results
wazuh/wazuh-dashboard-plugins pull request #7041
Opened 2024-10-01 10:11 UTC by JuanGarriuz

### Description

 Agent summary feature: when there are no agents, we want to hide the graph and show a message and a button indicating the user how to deploy an agent
 
### Issues Resolved

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7027

### Evidence

### Test

- Check overview with and without agents

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-10-01 13:53 UTC, guidomodarelli reviewed
TEST :green_circle: 
![image](https://github.com/user-attachments/assets/97c23b10-b8b8-47eb-b2f7-4ed376205f57)

2024-10-01 13:53 UTC, guidomodarelli commented on plugins/main/public/controllers/overview/components/stats.js
> +                          )}
Extract to a const

2024-10-01 13:53 UTC, guidomodarelli commented on plugins/main/public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
Is it necessary to remove the entire snapshot?

2024-10-02 09:06 UTC, asteriscos requested changes

2024-10-02 09:06 UTC, asteriscos commented on plugins/main/public/controllers/overview/components/stats.js
> +                      body={<p>Add agents to fleet to start monitoring</p>}
Please change the body description to:

```
body={
    <p>
      This instance has no agents registered.
      <br />
      Please deploy agents to begin monitoring your
      endpoints.
    </p>
  }
```

2024-10-02 14:20 UTC, asteriscos approved these changes
CR: :green_circle: 
Test: :green_circle:

2024-10-02 15:46 UTC, merged