Add filter by value to document details fields
wazuh/wazuh-dashboard-plugins pull request #7081
Opened 2024-10-07 16:58 UTC by guidomodarelli

### Description
Add filter-by-value to document details fields
 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7080

### Evidence

https://github.com/user-attachments/assets/605605aa-21ad-4f09-a40e-f3a48e22eb3e

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2024-10-15 19:45 UTC, Machi3mfl requested changes
## Error when open flyout button is clicked 

https://github.com/user-attachments/assets/e1557182-0bed-4cc9-b42f-e7ab7ac9d2fe

<img width="1511" alt="Screenshot 2024-10-15 at 4 45 48 PM" src="https://github.com/user-attachments/assets/d66abd34-c543-40ce-bb57-027ecff07d76">

2024-10-17 11:11 UTC, guidomodarelli commented
https://github.com/user-attachments/assets/8e5d5083-8bfa-42bb-911f-6601e29f3d61

2024-10-17 14:28 UTC, Desvelao commented
1. Adding a filter for a value that is a list for a field such as `rule.groups` causes the value to filter is wrong.
![image](https://github.com/user-attachments/assets/de154275-20b7-4195-930a-2659362caea3)
![image](https://github.com/user-attachments/assets/dffad874-a46c-4a35-8c9d-3467b54994fb)

Compare with Discover app:
![image](https://github.com/user-attachments/assets/8040a657-1d2e-4cb6-a3ed-2936acb25af9)
![image](https://github.com/user-attachments/assets/46b9f825-c6f5-4b4f-bf02-897219fe5fee)

2. Clicking in the button to add a filter from the document details does not close the flyout, despite the filter is added to the main search bar: 
![image](https://github.com/user-attachments/assets/7e004b9b-f1a8-4e32-8245-3e8a7c6f78c8)

In discover, adding a filter from the document details closes the flyout.

3. Reviewing a document in Discover app, I experienced some problems that should be reviewed.
![image](https://github.com/user-attachments/assets/b2e569c0-89d0-4fb0-8562-8016b1ffbec1)

4. I am not sure if this in Discover app could be caused by the Wazuh plugins or is a bug of Wazuh dashboard:
![image](https://github.com/user-attachments/assets/f7ce6777-80a6-43b1-91d6-3395ce442e20)

2024-10-17 15:07 UTC, Desvelao commented on plugins/main/public/components/common/doc-viewer/doc-viewer.scss
> +.osdDocViewerTable {
**nitpick**: avoid modifying styles from EUI components. Use a wrapper instead.

2024-10-17 18:54 UTC, guidomodarelli commented
# Update 2024/10/17

Clicking on the button to add a filter from the document details does not close the flyout, despite the filter is added to the main search bar

https://github.com/user-attachments/assets/7ee9d992-cabc-4b73-b316-44218f9965e1

2024-10-18 11:45 UTC, Desvelao commented
Table:

# wdp-pr-7081

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Table - Add filter from string value | :green_circle: | :black_circle: | :black_circle: |
| Table - Add negated filter from string value | :green_circle: | :black_circle: | :black_circle: |
| Table - Add filter from number value | :green_circle: | :black_circle: | :black_circle: |
| Table - Add negated filter from number value | :green_circle: | :black_circle: | :black_circle: |
| Table - Add filter from boolean value | :green_circle: | :black_circle: | :black_circle: |
| Table - Add negated filter from boolean value | :green_circle: | :black_circle: | :black_circle: |
| Table - Add filter from array of strings value | :black_circle: | :black_circle: | :black_circle: |
| Table - Add negated filter from array of strings value | :black_circle: | :black_circle: | :black_circle: |
| Table - Add filter from undefined value | :red_circle: | :black_circle: | :black_circle: |
| Table - Add negated filter from undefined value | :red_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Table - Add filter from string value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/f4829a08-32b2-430b-b758-8c79ce887691)
![image](https://github.com/user-attachments/assets/add8542e-2d9b-4351-bce3-f0ca13970321)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Table - Add negated filter from string value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/f4829a08-32b2-430b-b758-8c79ce887691)
![image](https://github.com/user-attachments/assets/30864a43-8e21-42e5-8d9c-ae99c7e03c61)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Table - Add filter from number value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/669a8929-4eac-450b-bbfd-b857bb379bf4)
![image](https://github.com/user-attachments/assets/dde1a947-77ec-4e2e-9508-2cec15545715)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Table - Add negated filter from number value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/669a8929-4eac-450b-bbfd-b857bb379bf4)
![image](https://github.com/user-attachments/assets/cb42c320-ae05-444c-a34a-e169c38216fe)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Table - Add filter from boolean value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/f0909daf-9bc8-491c-b0d0-65dce9d6e1c3)
![image](https://github.com/user-attachments/assets/e4157d9d-c79c-49d5-b2e6-465821e0cfca)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Table - Add negated filter from boolean value</summary>

Chrome - :green_circle:

![image](https://github.com/user-attachments/assets/f0909daf-9bc8-491c-b0d0-65dce9d6e1c3)
![image](https://github.com/user-attachments/assets/b777767d-8ce5-4ca1-afd3-5e17774e27a3)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Table - Add filter from array of strings value</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Table - Add negated filter from array of strings value</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Table - Add filter from undefined value</summary>

Chrome - :black_circle:
![image](https://github.com/user-attachments/assets/38447371-27e1-4f9f-81c8-abd5b2a39a3f)
![image](https://github.com/user-attachments/assets/31243080-f2a5-458f-9a65-b9572a59ce06)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:red_circle: Table - Add negated filter from undefined value</summary>

Chrome - :red_circle:
![image](https://github.com/user-attachments/assets/38447371-27e1-4f9f-81c8-abd5b2a39a3f)
![image](https://github.com/user-attachments/assets/8b167486-1db4-4279-89b4-13ae73277e26)

Firefox - :black_circle:

Safari - :black_circle:

</details>



Add filter - boolean


Add negated filter - boolean

2024-10-18 12:01 UTC, Desvelao commented
# wdp-pr-7081-misc

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Discover app styles no affected in table (legacy) | :green_circle: | :black_circle: | :black_circle: |
| Discover app styles no affected in document details (legacy) | :green_circle: | :black_circle: | :black_circle: |
| Discover app styles no affected in table (new) | :green_circle: | :black_circle: | :black_circle: |
| Discover app styles no affected in document details (new) | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Discover app styles no affected in table (legacy)</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/be05db6c-5183-4130-a726-1f01900438a3)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Discover app styles no affected in document details (legacy)</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/13d5ccad-21dc-4dfe-876c-e56380ac6c88)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Discover app styles no affected in table (new)</summary>

Chrome - :green_circle:

![image](https://github.com/user-attachments/assets/de0df675-0dec-4d5f-b0b6-a0df5f268e10)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Discover app styles no affected in document details (new)</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/9242d7f5-9e55-4718-b443-6a41dfe13879)

Firefox - :black_circle:

Safari - :black_circle:

</details>

2024-10-18 12:41 UTC, Desvelao commented
# wdp-pr-7081-doc-details

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Document details - Add filter from string value | :green_circle: | :black_circle: | :black_circle: |
| Document details - Add negated filter from string value | :green_circle: | :black_circle: | :black_circle: |
| Document details - Add filter from number value | :black_circle: | :black_circle: | :black_circle: |
| Document details - Add negated filter from number value | :black_circle: | :black_circle: | :black_circle: |
| Document details - Add filter from boolean value | :green_circle: | :black_circle: | :black_circle: |
| Document details - Add negated filter from boolean value | :green_circle: | :black_circle: | :black_circle: |
| Document details - Add filter from array of strings value | :green_circle: | :black_circle: | :black_circle: |
| Document details - Add negated filter from array of strings value | :green_circle: | :black_circle: | :black_circle: |
| Document details - Try to add "unindexed" value | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Document details - Add filter from string value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/c043182c-7fc1-47d7-ba18-aecfeb0b8858)
![image](https://github.com/user-attachments/assets/86205d66-981b-41f1-9dcb-5025321964d1)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Document details - Add negated filter from string value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/5e99bcdd-9951-4205-bb7c-c51d749b5ebb)
![image](https://github.com/user-attachments/assets/393cb46b-d1da-44a8-8001-aae315ea0be7)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Document details - Add filter from number value</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Document details - Add negated filter from number value</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Document details - Add filter from boolean value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/cb4940aa-76c2-4d3d-9962-806a4ed64a6a)
![image](https://github.com/user-attachments/assets/b0a445a8-a37a-4b9a-822b-34a8b4248ca4)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Document details - Add negated filter from boolean value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/f062aa81-78cf-4113-afca-62dc503474bd)
![image](https://github.com/user-attachments/assets/68e5e7de-d2ab-447e-aa69-4a42b3ef4eaa)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Document details - Add filter from array of strings value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/57275279-925a-42dd-a18f-87b42aac4dd7)
![image](https://github.com/user-attachments/assets/7594ec99-c45e-428c-97ad-e7bc21fa424a)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Document details - Add negated filter from array of strings value</summary>

Chrome - :green_circle:
![image](https://github.com/user-attachments/assets/8586be6d-47ca-4718-9813-1f5e795d5f4f)
![image](https://github.com/user-attachments/assets/77c8390f-af0d-4afd-86cc-55b8426e9481)

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Document details - Try to add "unindexed" value</summary>

Chrome - :green_circle:

![image](https://github.com/user-attachments/assets/b211c630-cd95-40bc-8ae3-ca3b88afbd03)

Firefox - :black_circle:

Safari - :black_circle:

</details>

2024-10-21 14:43 UTC, Desvelao commented on plugins/main/public/components/common/data-grid/data-grid-service.ts
> +    if (!value) return;
:nitpick**: this could ignore falsy values. Check how this is managed in OpenSearch Dashboards. We could be ignoring some use cases.

2024-10-24 14:38 UTC, asteriscos requested changes
Since the sync of Wazuh 4.9.1 changes there's some code that's no longer needed. Check which properties are being forwarded to components that no longer need it, since the data grid was removed from many modules.

2024-10-28 16:40 UTC, asteriscos approved these changes
CR: :green_circle: 
Test: :green_circle: 

Events
![Peek 2024-10-28 17-16](https://github.com/user-attachments/assets/f78827ca-f95e-4b79-bfb4-23f48933df91)

Vulnerabilities
![Peek 2024-10-28 17-27](https://github.com/user-attachments/assets/fa87d887-c114-4d00-aef1-fa9463505672)

FIM 
![Peek 2024-10-28 17-33](https://github.com/user-attachments/assets/b5b03576-f62c-4b60-91ee-53851dbfe963)

Control tab
![Peek 2024-10-28 17-36](https://github.com/user-attachments/assets/8fad8c35-d2c4-45e7-b18b-a020b173e17f)

Mitre ATT&CK - Framework
![Peek 2024-10-28 17-39](https://github.com/user-attachments/assets/baa58702-5b38-4b96-b28d-ca96a6af5546)

2024-10-29 09:53 UTC, Desvelao commented
# :green_circle: Test

![image](https://github.com/user-attachments/assets/f35eefac-9c61-463c-a505-d021ad4eae33)
![image](https://github.com/user-attachments/assets/ab6c56d8-9385-441a-b8ca-f6cb14ea97f7)

![image](https://github.com/user-attachments/assets/5b281551-42e1-4777-b95b-8349850f910a)
![image](https://github.com/user-attachments/assets/7c589943-5af8-4d43-a40c-d2984bb1c080)

FIM
![image](https://github.com/user-attachments/assets/fa08532f-87f3-4434-bc5e-ef25e882e9d0)
![image](https://github.com/user-attachments/assets/23a95c1a-21a2-4878-b7dd-580e7d5f0b3e)
![image](https://github.com/user-attachments/assets/f43f4dd4-36cf-486b-adcf-616f165bf9ba)

PCI DSS > Controls
![image](https://github.com/user-attachments/assets/4c6755ef-a9c5-42ac-91f4-06de031ac129)
![image](https://github.com/user-attachments/assets/1bb0cb67-f38d-4870-bcb9-1c84d1b123d3)

MITRE ATT&CK > Framework
![image](https://github.com/user-attachments/assets/2a805f83-7598-47f1-a60e-901c61fc12aa)
![image](https://github.com/user-attachments/assets/c5d7ab9c-307d-46d7-b3b3-3bf6ce05cb96)

2024-10-29 09:55 UTC, Desvelao approved these changes
LGTM!

2024-10-29 11:19 UTC, merged