All pages must include the pinned agent mechanic
wazuh/wazuh-dashboard-plugins pull request #7135
Opened 2024-10-29 11:25 UTC by guidomodarelli

### Description
All pages must include the pinned agent mechanic.
![image](https://github.com/user-attachments/assets/a8701270-10a9-4b05-a61a-a6c3a9d136f3)
 
### Issues Resolved
Closes #7130

### Evidence
![image](https://github.com/user-attachments/assets/fc94f49f-aaa9-4e34-8b45-cb2a8d73df3a)

![image](https://github.com/user-attachments/assets/5fc65e25-fade-436d-b14e-bc2f8b1115c7)

![image](https://github.com/user-attachments/assets/07594672-2a29-452d-bce6-66df7a3b6988)

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2024-10-29 17:21 UTC, asteriscos approved these changes
CR: :green_circle: 
Test: :green_circle: 


https://github.com/user-attachments/assets/4af6f839-ef12-46bb-b06b-720e0f62e169

2024-10-29 18:31 UTC, asteriscos approved these changes
Test: :green_circle: 

https://github.com/user-attachments/assets/b3d06c09-b470-440e-9f9a-5bb7858e13ad

2024-10-29 18:48 UTC, Machi3mfl submitted a review, later dismissed
LGTM!


https://github.com/user-attachments/assets/8efd72a8-25a3-4062-9142-81e51db58a7b

2024-10-29 19:30 UTC, chantal-kelm submitted a review, later dismissed
<img width="1792" alt="Captura de pantalla 2024-10-29 a la(s) 4 24 46 p  m" src="https://github.com/user-attachments/assets/1bc5449b-e271-4bbf-ab7c-ba9efb534386">
<img width="1792" alt="Captura de pantalla 2024-10-29 a la(s) 4 25 04 p  m" src="https://github.com/user-attachments/assets/df0051e8-1678-434c-ab87-749769591e9c">
<img width="1792" alt="Captura de pantalla 2024-10-29 a la(s) 4 25 14 p  m" src="https://github.com/user-attachments/assets/38f5af94-d944-4af3-8611-6dd5c80e1541">
<img width="1792" alt="Captura de pantalla 2024-10-29 a la(s) 4 25 22 p  m" src="https://github.com/user-attachments/assets/821e76bf-e0d9-4122-ba94-fd7bf211dc85">
<img width="1792" alt="Captura de pantalla 2024-10-29 a la(s) 4 25 51 p  m" src="https://github.com/user-attachments/assets/7165d03b-f5a7-4f1f-b2fb-0f49a2d42efd">

2024-10-30 08:03 UTC, JuanGarriuz commented
### Test

![image](https://github.com/user-attachments/assets/976508c7-27cd-472e-a03f-1c1b5c025cae)

https://github.com/user-attachments/assets/3500300e-421c-4fe8-9cd7-910f1059ecfc

2024-10-30 08:03 UTC, JuanGarriuz approved these changes
LGTM!!

2024-10-30 09:39 UTC, Desvelao commented on CHANGELOG.md
> +- Added pinned agent mechanic across all pages for consistent functionality [#7135](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7135)
**nitpick**: `all pages` reference it is not clear to me. Could you indicate where the button to "select" the agent was added instead?

2024-10-30 09:58 UTC, Desvelao commented
In `Inventory data` view, changing the selected agent should fetch the inventory data for the new selected agent and this request is not done according to my tests. Could you review it?

![image](https://github.com/user-attachments/assets/35bc2501-f3d1-4c65-a7c0-ae889a6104ff)

2024-10-30 10:10 UTC, JuanGarriuz commented
The breadcrumb does not redirect correctly when the agent is unpinned.


https://github.com/user-attachments/assets/2eb9c8e7-81e9-4dd1-a60a-168eb87e9174

2024-10-31 11:34 UTC, Machi3mfl commented
## Tests

### Verify the presence of the "Pinned Agent" button

1. Go to **Agents Management** » **Summary**.
2. Choose any agent.
3. Select "Inventory Data".
4. Verify the presence of the "Pinned Agent" button.
5. Select "Network".
6. Verify the presence of the "Pinned Agent" button.
7. Select to "Processes".
8. Verify the presence of the "Pinned Agent" button.
9. Return to the welcome page for agents.
10. Select "Stats".
11. Verify the presence of the "Pinned Agent" button.
12. Return to the welcome page for agents.
13. Select "Configuration".
14. Verify the presence of the "Pinned Agent" button.

### Clicking on unPinAgent should redirect you to `#/agents-preview`

1. Go to **Agents Management** » **Summary**.
2. Choose any agent.
3. Click on unPinAgent.
4. You should redirect to `#/agents-preview`.
5. Select "Inventory Data".
6. Select "Software" tab.
7. Click on unPinAgent.
8. You should redirect to `#/agents-preview`.
9. Choose any agent.
10. Select "Inventory Data".
11. Select "Network" tab.
12. Click on unPinAgent.
13. You should redirect to `#/agents-preview`.
14. Choose any agent.
15. Select "Inventory Data".
16. Select "Processes" tab.
17. Click on unPinAgent.
18. You should redirect to `#/agents-preview`.
19. Choose any agent.
20. Select "Stats".
21. Click on unPinAgent.
22. You should redirect to `#/agents-preview`.
23. Choose any agent.
24. Select "Configuration".
25. Click on unPinAgent.
26. You should redirect to `#/agents-preview`.

### Changing the pinned agent in "Configuration" should alter the data.

1. Go to **Agents Management** » **Summary**.
2. Choose any agent.
3. Select "Configuration".
4. Change the pinned agent.
5. Confirm that the data has been updated.

### Changing the pinned agent in "Stats" should alter the data.

1. Go to **Agents Management** » **Summary**.
2. Choose any agent.
3. Select "Stats".
4. Change the pinned agent.
5. Confirm that the data has been updated.

### Changing the pinned agent in "Inventory Data" should alter the data.

1. Go to **Agents Management** » **Summary**.
2. Choose any agent.
3. Select "Inventory Data".
4. Change the pinned agent.
5. Confirm that the data has been updated.

> [!WARNING]
> With Windows agent appears a new table

### Changing the pinned agent in "Inventory Data" should initiate a new request regarding the ribbon.

1. Go to **Agents Management** » **Summary**.
2. Choose any agent.
3. Select "Inventory Data".
4. Change the pinned agent.
5. Confirm that the request has been made again.

### Ensure that the line on the top bar is displayed across the entire bar, not just over the tabs.

2024-10-31 15:55 UTC, Machi3mfl approved these changes

2024-10-31 18:33 UTC, Machi3mfl approved these changes

2024-10-31 20:52 UTC, Machi3mfl approved these changes

2024-10-31 21:05 UTC, chantal-kelm requested changes
🔴 When unpinning an agent in the Processes tab, you are first redirected to the No agent is selected page and then to the endpoint summary page.

https://github.com/user-attachments/assets/87dde413-70da-48e1-8842-d9bee3693b96

2024-11-01 21:02 UTC, Machi3mfl commented
@guidomodarelli Do you remove the endpoints summary redirect when unpinning an agent? 

https://github.com/user-attachments/assets/6fb51840-b785-4e72-aa0e-3f6de4039948

2024-11-01 21:09 UTC, guidomodarelli commented
> @guidomodarelli Do you remove the endpoints summary redirect when unpinning an agent? 
> 
> https://github.com/user-attachments/assets/6fb51840-b785-4e72-aa0e-3f6de4039948
> 
> 
> 
> 

Yes, It's okay. It's to prevent flickering.

2024-11-04 12:23 UTC, JuanGarriuz commented
### Test Updated

https://github.com/user-attachments/assets/735feac6-1a87-47b9-b7e2-6ecd8777785d

2024-11-04 14:30 UTC, Machi3mfl submitted a review, later dismissed

2024-11-04 15:27 UTC, Desvelao commented on plugins/main/public/components/common/hooks/useGenericRequest.ts
> +    data: resolveData(response),
**suggestion**: apply the data transformation after fetching instead of each cycle.

2024-11-04 20:15 UTC, chantal-kelm approved these changes
https://github.com/user-attachments/assets/1cced97b-e8c6-432d-bd2a-821b1f6b17ac

https://github.com/user-attachments/assets/6751fa98-8713-4960-bcb2-a70f95752137

2024-11-05 13:23 UTC, chantal-kelm approved these changes

2024-11-05 14:32 UTC, merged