Migrate wazuh.yml configuration to opensearch_dashboards.yml
wazuh/wazuh-dashboard-plugins pull request #7175
Opened 2024-11-25 19:02 UTC by Machi3mfl

### Description

This PR move the location of the wazuh.yml to opensearch_dashboards.yml
 
Closes https://github.com/wazuh/wazuh-dashboard/issues/339

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-12-23 10:57 UTC, JuanGarriuz commented
## Pre-test

Something is going wrong with the environment loading.

https://github.com/user-attachments/assets/68644e9e-604c-4a17-9d40-5b827f961a1e



## Test 

### Check the Dashboard `Management > Advanced settings` validations

| Field                          | Type                  | Validations   | Chrome | Firefox | Safari |
|-------------------|----------------|----------------------|---------------|----------------|-----------------------|
| alerts.sample.prefix            | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>', '#', '*') | ⚫    | ⚫    | ⚫   |
| configuration.ui_api_editable   | EpluginSettingType.switch| - Boolean  | ⚫    | ⚫    | ⚫   |
| cron.prefix                     | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>','#', '*') | ⚫    | ⚫    | ⚫   |
| customization.enabled           | EpluginSettingType.switch| - Boolean      | ⚫    | ⚫    | ⚫   |
| enrollment.dns                  | EpluginSettingType.text| - String<br>- serverAddressHostnameFQDNIPv4IPv6                             | ⚫    | ⚫    | ⚫   |
| enrollment.password              | EpluginSettingType.text| - String                                                                   | ⚫    | ⚫    | ⚫   |
| hideManagerAlerts                | EpluginSettingType.switch| - Boolean                                                                   | ⚫    | ⚫    | ⚫   |
| ip.ignore                       | EpluginSettingType.editor| - Array of:<br>  - String<br>  - notEmpty<br>  - noSpaces<br>  - noLiteralString('.', '..')<br>  - noStartsWith('-', '_', '+', '.')<br>  - noInvalidCharacters('\\', '/', '?', '"', '<', '>', '#') | ⚫    | ⚫    | ⚫   |
| ip.selector                     | EpluginSettingType.switch| - Boolean                                                                   | ⚫    | ⚫    | ⚫   |
| wazuh.updates.disabled          | EpluginSettingType.switch| - Boolean                                                                   | ⚫    | ⚫    | ⚫   |
| pattern                         | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noLiteralString('.', '..')<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>', '#') | ⚫    | ⚫    | ⚫   |
| timeout                         | EpluginSettingType.number| - Number (min: 1500, integer)                                             | ⚫    | ⚫    | ⚫   |
| vulnerabilities.pattern          | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noLiteralString('.', '..')<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>', ',', '#') | ⚫    | ⚫    | ⚫   |

### Check the `opensearch_dashboards.yml` validations


| Field                          | Type                  | Validations   | Chrome | Firefox | Safari |
|-------------------|----------------|----------------------|---------------|----------------|-----------------------|
| hosts                           | EpluginSettingType.objectOf|`url`: <br>  - String<br>  - notEmpty<br>  `port`: <br>  - Number (0-65535)<br> `username`: <br>  - String<br>  - notEmpty<br> `password`: <br>  - String<br>  - notEmpty<br> `run_as`: <br>  - Boolean | ⚫    | ⚫    | ⚫   |

2024-12-23 14:43 UTC, chantal-kelm submitted a review, later dismissed
CR: ✅ 
TEST: ✅ 

<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 41 11 a  m" src="https://github.com/user-attachments/assets/a4cbe5fd-fad3-41b5-9da2-77be83ec22ee" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 40 56 a  m" src="https://github.com/user-attachments/assets/8dd8ea74-11e0-4c7d-865e-4a93d2803cc7" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 40 45 a  m" src="https://github.com/user-attachments/assets/fdb19db9-5ea0-4c8b-88c7-f35244e8e38d" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 39 57 a  m" src="https://github.com/user-attachments/assets/bedad11a-e422-4d40-b7f8-5045505e467c" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 39 35 a  m" src="https://github.com/user-attachments/assets/d93faee4-4f73-4ade-9f9d-8c6840981ebe" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 39 22 a  m" src="https://github.com/user-attachments/assets/930d176c-48a7-4f84-9ee1-85a80b9e6d2a" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 39 09 a  m" src="https://github.com/user-attachments/assets/a3928dc6-fbfc-4bf4-b3d5-6bf31255fa05" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 38 22 a  m" src="https://github.com/user-attachments/assets/637dc6c5-4f03-4070-b4be-d5d38b81b775" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 11 38 06 a  m" src="https://github.com/user-attachments/assets/96e2ab58-19f6-4758-8365-83a4bb6f4902" />

2024-12-23 15:19 UTC, JuanGarriuz approved these changes
LGTM!!

2024-12-23 21:02 UTC, chantal-kelm submitted a review, later dismissed
CR: ✅ 
TEST: ✅ 

<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 6 00 58 p  m" src="https://github.com/user-attachments/assets/a88bc830-2133-4a39-bca4-0acc0860aee2" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 6 00 45 p  m" src="https://github.com/user-attachments/assets/d3182b01-a40e-45bb-bd28-447ee80d67b0" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 6 00 28 p  m" src="https://github.com/user-attachments/assets/f49fb337-58f2-4d23-a043-58044a7f116c" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 6 00 03 p  m" src="https://github.com/user-attachments/assets/7ad89859-1702-4a48-922e-d4387ffa951d" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 5 59 44 p  m" src="https://github.com/user-attachments/assets/11f211ac-bfdc-49dc-a17b-c5ed11063f62" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 5 59 24 p  m" src="https://github.com/user-attachments/assets/b4b14498-0b68-47f7-a167-4a51c74ff385" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 5 59 00 p  m" src="https://github.com/user-attachments/assets/94ae8759-ce9a-46ec-af26-007cb3e20a07" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 5 57 05 p  m" src="https://github.com/user-attachments/assets/a9377bbf-7e16-494f-9ce8-7cfe6b573ff9" />
<img width="1792" alt="Captura de pantalla 2024-12-23 a la(s) 5 56 23 p  m" src="https://github.com/user-attachments/assets/e2bb78a9-655a-4b4d-a4d8-0fbd57863bed" />

2024-12-24 14:09 UTC, JuanGarriuz submitted a review, later dismissed

2024-12-24 14:31 UTC, chantal-kelm submitted a review, later dismissed
CR: ✅ 
TEST: ✅ 

<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 30 16 a  m" src="https://github.com/user-attachments/assets/846ad690-72a8-4502-9252-1d0c943931c5" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 30 01 a  m" src="https://github.com/user-attachments/assets/cc2e96cb-a039-439e-9cb0-39a19f8a314a" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 29 44 a  m" src="https://github.com/user-attachments/assets/4e7e9eda-bc2f-467d-978f-dda86fc14edf" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 29 09 a  m" src="https://github.com/user-attachments/assets/71ae4879-1e8e-411e-82c1-43b7df05e13d" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 28 39 a  m" src="https://github.com/user-attachments/assets/d16b71dd-c5e6-4845-bbb4-b8d78f7e269d" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 28 02 a  m" src="https://github.com/user-attachments/assets/5e68f561-f955-4a08-9a34-27f06becdfe2" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 27 46 a  m" src="https://github.com/user-attachments/assets/771ef368-eebb-4293-9c86-3c84d7ba6f76" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 27 30 a  m" src="https://github.com/user-attachments/assets/25fb38c9-2987-44e8-ba31-09e076d416ce" />
<img width="1792" alt="Captura de pantalla 2024-12-24 a la(s) 11 27 12 a  m" src="https://github.com/user-attachments/assets/1ced50b9-95ef-4d1a-b8ea-4867870af4b9" />

2024-12-24 16:26 UTC, guidomodarelli requested changes

2024-12-24 16:26 UTC, guidomodarelli commented on plugins/wazuh-core/common/services/configuration/configuration.test.ts
> +    (mockConfigurationStore.getAll as jest.Mock).mockRejectedValue(
```suggestion
    mockConfigurationStore.getAll.mockRejectedValue(
```

2024-12-24 16:26 UTC, guidomodarelli commented on plugins/wazuh-core/common/services/configuration/configuration.test.ts
> +}
Relocate this to a new file within `wazuh-core/test/__mocks__/logger.ts`.

2024-12-24 16:26 UTC, guidomodarelli commented on plugins/wazuh-core/common/services/configuration/configuration-store.test.ts
> +}
Relocate this to a new file within `wazuh-core/test/__mocks__/logger.ts`.

2024-12-24 17:16 UTC, Machi3mfl commented on plugins/wazuh-core/server/services/manage-hosts.ts
> +          allowRunAs = responseAllowRunAs.data.data.affected_items[0].allowRunAs
This is my fault, thanks for noticing. I replace the allow_run_as constant to removing the _, and when replacing wrongly replace what comes from the api

2024-12-26 17:01 UTC, Machi3mfl commented on plugins/wazuh-core/common/settings-adapter.ts
> +    throw new Error('Invalid settings or type');
This could be improved when we implement a new error solution.

2024-12-26 17:01 UTC, Machi3mfl commented on plugins/wazuh-core/common/settings-adapter.ts
> +        throw new Error('Invalid objectOf setting');
This could be improved when we implement a new error solution.

2024-12-26 17:01 UTC, Machi3mfl commented on plugins/wazuh-core/common/settings-adapter.ts
> +    throw new Error('Invalid setting');
This could be improved when we implement a new error solution.

2024-12-26 17:05 UTC, Machi3mfl commented on plugins/wazuh-core/common/services/configuration/configuration-store.ts
> +      throw new Error(`Provider ${name} not found`);
This could be improved when we implement a new error solution.

2024-12-26 17:05 UTC, Machi3mfl commented on plugins/wazuh-core/common/services/configuration/configuration-store.ts
> +      );
This could be improved when we implement a new error solution.

2024-12-26 19:34 UTC, guidomodarelli commented
# Test

### Check the Dashboard `Management > Advanced settings` validations

| Field                          | Type                  | Validations   | Chrome | Firefox | Safari |
|-------------------|----------------|----------------------|---------------|----------------|-----------------------|
| alerts.sample.prefix            | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>', '#', '*') | ⚫    | ⚫    | ⚫   |
| configuration.ui_api_editable   | EpluginSettingType.switch| - Boolean  | ⚫    | ⚫    | ⚫   |
| cron.prefix                     | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>','#', '*') | ⚫    | ⚫    | ⚫   |
| customization.enabled           | EpluginSettingType.switch| - Boolean      | ⚫    | ⚫    | ⚫   |
| enrollment.dns                  | EpluginSettingType.text| - String<br>- serverAddressHostnameFQDNIPv4IPv6                             | ⚫    | ⚫    | ⚫   |
| enrollment.password              | EpluginSettingType.text| - String                                                                   | ⚫    | ⚫    | ⚫   |
| hideManagerAlerts                | EpluginSettingType.switch| - Boolean                                                                   | ⚫    | ⚫    | ⚫   |
| ip.ignore                       | EpluginSettingType.editor| - Array of:<br>  - String<br>  - notEmpty<br>  - noSpaces<br>  - noLiteralString('.', '..')<br>  - noStartsWith('-', '_', '+', '.')<br>  - noInvalidCharacters('\\', '/', '?', '"', '<', '>', '#') | ⚫    | ⚫    | ⚫   |
| ip.selector                     | EpluginSettingType.switch| - Boolean                                                                   | ⚫    | ⚫    | ⚫   |
| wazuh.updates.disabled          | EpluginSettingType.switch| - Boolean                                                                   | ⚫    | ⚫    | ⚫   |
| pattern                         | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noLiteralString('.', '..')<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>', '#') | ⚫    | ⚫    | ⚫   |
| timeout                         | EpluginSettingType.number| - Number (min: 1500, integer)                                             | ⚫    | ⚫    | ⚫   |
| vulnerabilities.pattern          | EpluginSettingType.text| - String<br>- notEmpty<br>- noSpaces<br>- noLiteralString('.', '..')<br>- noStartsWith('-', '_', '+', '.')<br>- noInvalidCharacters('\\', '/', '?', '"', '<', '>', ',', '#') | ⚫    | ⚫    | ⚫   |

### Check the `opensearch_dashboards.yml` validations


| Field                          | Type                  | Validations   | Chrome | Firefox | Safari |
|-------------------|----------------|----------------------|---------------|----------------|-----------------------|
| hosts                           | EpluginSettingType.objectOf|`url`: <br>  - String<br>  - notEmpty<br>  `port`: <br>  - Number (0-65535)<br> `username`: <br>  - String<br>  - notEmpty<br> `password`: <br>  - String<br>  - notEmpty<br> `run_as`: <br>  - Boolean | ⚫    | ⚫    | ⚫   |

<details><summary><b>alerts.sample.prefix</b></summary>
<br />
  **notEmpty**
  
  ![image](https://github.com/user-attachments/assets/656d30d1-819e-48bc-9286-618a8b5bd600)

  **noSpaces**
    
  ![image](https://github.com/user-attachments/assets/4273d8e0-9895-4070-8081-dc5932eb6527)

  **noStartsWith('-', '_', '+', '.')**
  
  ![image](https://github.com/user-attachments/assets/94d15755-062a-4955-8fef-ed8785b06529)

  ![image](https://github.com/user-attachments/assets/350ee059-31ac-47f2-a3b1-98a98c113ef0)

  ![image](https://github.com/user-attachments/assets/9c95da45-4a9f-46f3-bb47-3df780bbb926)

  ![image](https://github.com/user-attachments/assets/5eb86bf2-2919-4868-bebc-e31d8036ca90)

</details>

2024-12-30 15:42 UTC, Machi3mfl commented
# Fixed opensearch_dashboards.yml » hosts validation

### Host with negative value on yml

<img width="429" alt="Screenshot 2024-12-30 at 12 20 33 PM" src="https://github.com/user-attachments/assets/5d54e02b-7ace-4b68-969e-02920f978736" />

### Validation error on start osd server

<img width="938" alt="Screenshot 2024-12-30 at 12 20 19 PM" src="https://github.com/user-attachments/assets/5e9906e0-0bd4-4560-b898-3617921414f8" />

C.C: @guidomodarelli.

2024-12-30 15:52 UTC, guidomodarelli commented
### Check the `opensearch_dashboards.yml` validations

| Field                          | Type                  | Validations   | Chrome | Firefox | Safari |
|-------------------|----------------|----------------------|---------------|----------------|-----------------------|
| hosts                           | EpluginSettingType.objectOf|`url`: <br>  - String<br>  - notEmpty<br>  `port`: <br>  - Number (0-65535)<br> `username`: <br>  - String<br>  - notEmpty<br> `password`: <br>  - String<br>  - notEmpty<br> `run_as`: <br>  - Boolean | 🟢    | ⚫    | ⚫   |

  `port: -1` 🟢
  
  ![image](https://github.com/user-attachments/assets/57725082-ff11-4495-8280-4254e1a18a2b)
  ![image](https://github.com/user-attachments/assets/cc4904d9-60bd-4a51-83a6-66532ce106b4)

2024-12-30 15:53 UTC, JuanGarriuz approved these changes

2024-12-30 15:56 UTC, guidomodarelli approved these changes
LGTM 🟢

2024-12-30 16:52 UTC, merged