Improve-agent-details-page
wazuh/wazuh-dashboard-plugins pull request #7196
Opened 2024-12-05 17:57 UTC by guidomodarelli

### Description

We want to refine some aspects of the Agent dashboard to enhance the use experience. To achieve this we will do the following tasks.

### Issues Resolved

Closes https://github.com/wazuh/wazuh-dashboard-plugins/issues/7193

### Evidence

[Provide screenshots or videos to prove this PR solves the issues]

### Test

[Provide instructions to test this PR]

### Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2024-12-06 16:09 UTC, Tostti requested changes
# Test 🔴 
# CR 🟢 


| Test | Firefox | Chrome| Safari| 
|---|---|---|---|
| Adjusted the height of the event count evolution visualization.|🟢 |🟢|:black_circle:|
|Standardized padding for the "Top 5 Packages" table to align with other tables.|🟢|🟢|:black_circle:|
| Reduced the width of small fields in the Agent Info ribbon for a more compact layout.|🔴 |🔴 |:black_circle:|
|Replaced "Malware Detection" with "Vulnerability Detection" in the agent's pinned navigation menu.|🟢 |🟢|:black_circle:|
|Aligned "Vulnerability Detection" KPIs to the left.|🟢 |🟢|:black_circle:|


###  Adjusted the height of the event count evolution visualization. 🟢 

<details>

**Firefox**
![imagen](https://github.com/user-attachments/assets/be244cb5-400a-4edc-a357-f2c8f56a9ce1)

**Chrome**
![imagen](https://github.com/user-attachments/assets/3c9241c2-fbee-448f-828c-ba0b99e91b0b)

</details>


###  Standardized padding for the "Top 5 Packages" table to align with other tables. 🟢 

<details>

**Firefox**
![imagen](https://github.com/user-attachments/assets/a5543708-fe7f-41f7-b0fd-57cbe7ff8982)

**Chrome**
![imagen](https://github.com/user-attachments/assets/76043628-68bb-4fd1-8ae8-451c725e6112)

</details>

###  Reduced the width of small fields in the Agent Info ribbon for a more compact layout. 🔴 

<details>

On IPv6, the address superposes with `Version`

**Firefox**

![imagen](https://github.com/user-attachments/assets/a38689bc-a12c-4e2a-9764-494aeca1ee16)

**Chrome**
![imagen](https://github.com/user-attachments/assets/6f07529d-8933-43e6-a405-13f8f836ba78)

</details>

###  Replaced "Malware Detection" with "Vulnerability Detection" in the agent's pinned navigation menu. 🟢 

<details>

**Firefox**
![imagen](https://github.com/user-attachments/assets/cdf9e4f1-97fa-44f5-836a-ce4851de7d9f)


**Chrome**
![imagen](https://github.com/user-attachments/assets/a523b7f0-e9b1-41fc-93f9-7d99ad88eb59)

</details>

###  Aligned "Vulnerability Detection" KPIs to the left. 🟢 

<details>

**Firefox**
![imagen](https://github.com/user-attachments/assets/5ac9c579-43bd-4142-8677-558eff138d4e)

**Chrome**
![imagen](https://github.com/user-attachments/assets/330aad97-e2a2-449f-9441-25e5f8c873ac)

</details>

2024-12-09 09:56 UTC, gdiazlo commented
The padding / left margin on the left aligned vulnerability count panel looks smaller than it should be

2024-12-10 11:58 UTC, Tostti submitted a review, later dismissed
Issue reported in https://github.com/wazuh/wazuh-dashboard-plugins/pull/7196#pullrequestreview-2485266941solved. 

## Test 🟢 
![imagen](https://github.com/user-attachments/assets/1f4cd94b-18f1-488c-aa55-35f11403ed17)

## CR 🟢 

LGTM

2024-12-10 18:32 UTC, chantal-kelm requested changes
🔴 Reduced the width of small fields in the Agent Info ribbon for a more compact layout.

<img width="1792" alt="Captura de pantalla 2024-12-10 a la(s) 3 21 56 p  m" src="https://github.com/user-attachments/assets/b7785654-a16c-453e-b04c-f2e6ed2b562a">

🔴 Replaced "Malware Detection" with "Vulnerability Detection" in the agent's pinned navigation menu.

<img width="1792" alt="Captura de pantalla 2024-12-10 a la(s) 3 17 19 p  m" src="https://github.com/user-attachments/assets/36cd5664-ec27-4df2-9d74-ab4ce61463f5">

2024-12-10 19:47 UTC, chantal-kelm submitted a review, later dismissed
CR: ✅ 
TEST: ✅ 

<img width="1792" alt="Captura de pantalla 2024-12-10 a la(s) 4 46 04 p  m" src="https://github.com/user-attachments/assets/3733f1a5-4e3d-4c0c-9d84-a46920fb078e">

2024-12-11 11:42 UTC, Desvelao commented on plugins/main/public/components/common/ribbon/ribbon-item.tsx
> +  item.style = { ...item.style, fontSize: FONT_SIZE };
**nitpick**: this seems to redefine a prop and this is a bad practice. Create a new object/variable to append the `fontSize` definition.

2024-12-11 11:42 UTC, Desvelao commented on plugins/main/public/components/common/ribbon/ribbon-item.tsx
> +    item.render = () => {
**nitpick**: this seems to redefine a prop and this is a bad practice. Create a new object/variable to append the `render` definition.

2024-12-11 17:53 UTC, chantal-kelm submitted a review, later dismissed
CR: ✅ 
TEST: ✅ 

<img width="1792" alt="Captura de pantalla 2024-12-11 a la(s) 2 49 55 p  m" src="https://github.com/user-attachments/assets/f0ddded4-2bd7-4468-b159-af06858b50ae" />

2024-12-11 18:06 UTC, asteriscos submitted a review, later dismissed
CR: :green_circle: 
Test: :green_circle: 

#### Firefox
![image](https://github.com/user-attachments/assets/e59a5d35-58d0-459a-be22-c061cc3a6bc0)


#### Chrome

![image](https://github.com/user-attachments/assets/7faaa87f-d0f6-49d8-ba10-b1f4afee9e3e)

2024-12-11 18:07 UTC, asteriscos submitted a review, later dismissed

2024-12-11 18:10 UTC, chantal-kelm submitted a review, later dismissed
<img width="1792" alt="Captura de pantalla 2024-12-11 a la(s) 3 09 37 p  m" src="https://github.com/user-attachments/assets/6905220b-75a9-42a8-9a3d-9627c562daed" />

2024-12-11 18:19 UTC, chantal-kelm approved these changes

2024-12-11 18:21 UTC, asteriscos approved these changes

2024-12-11 18:30 UTC, merged